version: '3.9'

services:
  s3:
    image: localstack/localstack
    container_name: s3
    network_mode: bridge
    ports:
      - 4566:4566
      - 9090:8080
    environment:
      - SERVICES=s3,sns,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-2
      - PORT_WEB_UI=8080
    volumes:
      - "localstack-vol:/tmp/localstack"
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=FileStorageApp
      - POSTGRES_PASSWORD=change
      - POSTGRES_DB=FileStorageApp
    ports:
      - "5432:5432"


volumes:
  localstack-vol:
